apiVersion: apps/v1
kind: Deployment
metadata:
  name: travis-deployment
  labels:
    app: travis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travis
  template:
    metadata:
      labels:
        app: travis
    spec:
      containers:
      - name: travis
        image: travis-demo
        ports:
        - containerPort: 80
